sudo: required

services:
  - docker

before_install:
  - docker build -t luoxiao78/multi-client-test -f ./client/Dockerfile.dev ./client
  # - docker build -t luoxiao78/multi-server-test -f ./server/Dockerfile.dev ./server
  # - docker build -t luoxiao78/multi-worker-test -f ./worker/Dockerfile.dev ./worker
  # - docker build -t luoxiao78/multi-nginx-test -f ./nginx/Dockerfile.dev ./nginx
    
script:
  - docker run -e CI=true luoxiao78/multi-client-test npm test
  # - docker run luoxiao78/multi-server-test npm run test
  # - docker run luoxiao78/multi-worker-test npm run test
  # - docker run luoxiao78/multi-nginx-test npm run test

after_success:
  - docker build luoxiao78/multi-client ./client
  - docker build luoxiao78/multi-server ./server
  - docker build luoxiao78/multi-worker ./worker
  - docker build luoxiao78/multi-nginx ./nginx
  - echo $DOCKER_PASS | docker login -u $DOCKER_ID --password_stdin
  - docker push luoxiao78/multi-client
  - docker push luoxiao78/multi-server
  - docker push luoxiao78/multi-worker
  - docker push luoxiao78/multi-nginx
